// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import path from "path";
import fs from "fs";

function findSchema(): string {
  const candidates = [
    path.join(__dirname, "prisma", "schema.prisma"),
    path.join(process.cwd(), "prisma", "schema.prisma"),
    path.join(process.cwd(), "apps", "backend", "prisma", "schema.prisma"),
  ];
  const found = candidates.find((p) => fs.existsSync(p));
  if (!found) {
    throw new Error(
      `No se encontró ningún schema.prisma en las rutas esperadas: ${candidates.join(", ")}`
    );
  }
  return found;
}

const schemaPath = findSchema();

export default defineConfig({
  schema: schemaPath,
  migrations: {
    path: path.join(path.dirname(schemaPath), "migrations"),
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
