import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { PublicacionOrderByWithRelationInputObjectSchema as PublicacionOrderByWithRelationInputObjectSchema } from './objects/PublicacionOrderByWithRelationInput.schema';
import { PublicacionWhereInputObjectSchema as PublicacionWhereInputObjectSchema } from './objects/PublicacionWhereInput.schema';
import { PublicacionWhereUniqueInputObjectSchema as PublicacionWhereUniqueInputObjectSchema } from './objects/PublicacionWhereUniqueInput.schema';
import { PublicacionCountAggregateInputObjectSchema as PublicacionCountAggregateInputObjectSchema } from './objects/PublicacionCountAggregateInput.schema';
import { PublicacionMinAggregateInputObjectSchema as PublicacionMinAggregateInputObjectSchema } from './objects/PublicacionMinAggregateInput.schema';
import { PublicacionMaxAggregateInputObjectSchema as PublicacionMaxAggregateInputObjectSchema } from './objects/PublicacionMaxAggregateInput.schema';
import { PublicacionAvgAggregateInputObjectSchema as PublicacionAvgAggregateInputObjectSchema } from './objects/PublicacionAvgAggregateInput.schema';
import { PublicacionSumAggregateInputObjectSchema as PublicacionSumAggregateInputObjectSchema } from './objects/PublicacionSumAggregateInput.schema';

export const PublicacionAggregateSchema: z.ZodType<Prisma.PublicacionAggregateArgs> = z.object({ orderBy: z.union([PublicacionOrderByWithRelationInputObjectSchema, PublicacionOrderByWithRelationInputObjectSchema.array()]).optional(), where: PublicacionWhereInputObjectSchema.optional(), cursor: PublicacionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PublicacionCountAggregateInputObjectSchema ]).optional(), _min: PublicacionMinAggregateInputObjectSchema.optional(), _max: PublicacionMaxAggregateInputObjectSchema.optional(), _avg: PublicacionAvgAggregateInputObjectSchema.optional(), _sum: PublicacionSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PublicacionAggregateArgs>;

export const PublicacionAggregateZodSchema = z.object({ orderBy: z.union([PublicacionOrderByWithRelationInputObjectSchema, PublicacionOrderByWithRelationInputObjectSchema.array()]).optional(), where: PublicacionWhereInputObjectSchema.optional(), cursor: PublicacionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), PublicacionCountAggregateInputObjectSchema ]).optional(), _min: PublicacionMinAggregateInputObjectSchema.optional(), _max: PublicacionMaxAggregateInputObjectSchema.optional(), _avg: PublicacionAvgAggregateInputObjectSchema.optional(), _sum: PublicacionSumAggregateInputObjectSchema.optional() }).strict();