import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { VendedorOrderByWithRelationInputObjectSchema as VendedorOrderByWithRelationInputObjectSchema } from './objects/VendedorOrderByWithRelationInput.schema';
import { VendedorWhereInputObjectSchema as VendedorWhereInputObjectSchema } from './objects/VendedorWhereInput.schema';
import { VendedorWhereUniqueInputObjectSchema as VendedorWhereUniqueInputObjectSchema } from './objects/VendedorWhereUniqueInput.schema';
import { VendedorCountAggregateInputObjectSchema as VendedorCountAggregateInputObjectSchema } from './objects/VendedorCountAggregateInput.schema';
import { VendedorMinAggregateInputObjectSchema as VendedorMinAggregateInputObjectSchema } from './objects/VendedorMinAggregateInput.schema';
import { VendedorMaxAggregateInputObjectSchema as VendedorMaxAggregateInputObjectSchema } from './objects/VendedorMaxAggregateInput.schema';
import { VendedorAvgAggregateInputObjectSchema as VendedorAvgAggregateInputObjectSchema } from './objects/VendedorAvgAggregateInput.schema';
import { VendedorSumAggregateInputObjectSchema as VendedorSumAggregateInputObjectSchema } from './objects/VendedorSumAggregateInput.schema';

export const VendedorAggregateSchema: z.ZodType<Prisma.VendedorAggregateArgs> = z.object({ orderBy: z.union([VendedorOrderByWithRelationInputObjectSchema, VendedorOrderByWithRelationInputObjectSchema.array()]).optional(), where: VendedorWhereInputObjectSchema.optional(), cursor: VendedorWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), VendedorCountAggregateInputObjectSchema ]).optional(), _min: VendedorMinAggregateInputObjectSchema.optional(), _max: VendedorMaxAggregateInputObjectSchema.optional(), _avg: VendedorAvgAggregateInputObjectSchema.optional(), _sum: VendedorSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.VendedorAggregateArgs>;

export const VendedorAggregateZodSchema = z.object({ orderBy: z.union([VendedorOrderByWithRelationInputObjectSchema, VendedorOrderByWithRelationInputObjectSchema.array()]).optional(), where: VendedorWhereInputObjectSchema.optional(), cursor: VendedorWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), VendedorCountAggregateInputObjectSchema ]).optional(), _min: VendedorMinAggregateInputObjectSchema.optional(), _max: VendedorMaxAggregateInputObjectSchema.optional(), _avg: VendedorAvgAggregateInputObjectSchema.optional(), _sum: VendedorSumAggregateInputObjectSchema.optional() }).strict();